-- =====================================================================
-- StayEase Hotel Reservation & Booking Management System
-- MySQL schema + sample data
-- =====================================================================

DROP DATABASE IF EXISTS stayease_db;
CREATE DATABASE stayease_db;
USE stayease_db;

-- ---------------------------------------------------------------------
-- Staff / system users (login)
-- ---------------------------------------------------------------------
CREATE TABLE users (
    user_id      INT AUTO_INCREMENT PRIMARY KEY,
    username     VARCHAR(50)  NOT NULL UNIQUE,
    password     VARCHAR(255) NOT NULL,   -- SHA-256 hash, see PasswordUtil
    full_name    VARCHAR(100) NOT NULL,
    role         ENUM('ADMIN','RECEPTIONIST') NOT NULL DEFAULT 'RECEPTIONIST',
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------
-- Guests
-- ---------------------------------------------------------------------
CREATE TABLE guests (
    guest_id      INT AUTO_INCREMENT PRIMARY KEY,
    first_name    VARCHAR(60)  NOT NULL,
    last_name     VARCHAR(60)  NOT NULL,
    nic_passport  VARCHAR(30)  NOT NULL UNIQUE,
    phone         VARCHAR(20)  NOT NULL,
    email         VARCHAR(100),
    address       VARCHAR(200),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------
-- Rooms
-- ---------------------------------------------------------------------
CREATE TABLE rooms (
    room_id        INT AUTO_INCREMENT PRIMARY KEY,
    room_number    VARCHAR(10) NOT NULL UNIQUE,
    room_type      ENUM('SINGLE','DOUBLE','DELUXE','SUITE') NOT NULL,
    rate_per_night DECIMAL(10,2) NOT NULL,
    capacity       INT NOT NULL DEFAULT 2,
    status         ENUM('AVAILABLE','OCCUPIED','MAINTENANCE') NOT NULL DEFAULT 'AVAILABLE',
    description    VARCHAR(255)
);

-- ---------------------------------------------------------------------
-- Bookings (major transaction)
-- ---------------------------------------------------------------------
CREATE TABLE bookings (
    booking_id     INT AUTO_INCREMENT PRIMARY KEY,
    guest_id       INT NOT NULL,
    room_id        INT NOT NULL,
    check_in_date  DATE NOT NULL,
    check_out_date DATE NOT NULL,
    num_guests     INT NOT NULL DEFAULT 1,
    status         ENUM('CONFIRMED','CHECKED_IN','CHECKED_OUT','CANCELLED') NOT NULL DEFAULT 'CONFIRMED',
    total_amount   DECIMAL(10,2) NOT NULL,
    created_by     INT NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_guest FOREIGN KEY (guest_id) REFERENCES guests(guest_id),
    CONSTRAINT fk_booking_room  FOREIGN KEY (room_id)  REFERENCES rooms(room_id),
    CONSTRAINT fk_booking_user  FOREIGN KEY (created_by) REFERENCES users(user_id)
);

-- ---------------------------------------------------------------------
-- Payments
-- ---------------------------------------------------------------------
CREATE TABLE payments (
    payment_id     INT AUTO_INCREMENT PRIMARY KEY,
    booking_id     INT NOT NULL,
    amount         DECIMAL(10,2) NOT NULL,
    payment_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    payment_method ENUM('CASH','CARD','ONLINE') NOT NULL,
    received_by    INT NOT NULL,
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
    CONSTRAINT fk_payment_user    FOREIGN KEY (received_by) REFERENCES users(user_id)
);

-- =====================================================================
-- Sample data
-- =====================================================================

-- Default login: username "admin", password "admin123"
-- (SHA-256 of "admin123" -- generated by com.stayease.util.PasswordUtil.hash)
INSERT INTO users (username, password, full_name, role) VALUES
('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'System Administrator', 'ADMIN'),
('reception1', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Nimal Perera', 'RECEPTIONIST');

INSERT INTO rooms (room_number, room_type, rate_per_night, capacity, status, description) VALUES
('101', 'SINGLE', 8500.00, 1, 'AVAILABLE', 'Cozy single room, garden view'),
('102', 'SINGLE', 8500.00, 1, 'AVAILABLE', 'Cozy single room, garden view'),
('201', 'DOUBLE', 13500.00, 2, 'AVAILABLE', 'Double room with balcony'),
('202', 'DOUBLE', 13500.00, 2, 'OCCUPIED', 'Double room with balcony'),
('301', 'DELUXE', 21000.00, 3, 'AVAILABLE', 'Deluxe room, sea view'),
('401', 'SUITE', 35000.00, 4, 'AVAILABLE', 'Executive suite with living area');

INSERT INTO guests (first_name, last_name, nic_passport, phone, email, address) VALUES
('Kasun', 'Fernando', '199512345678', '0771234567', 'kasun.f@example.com', '12 Galle Road, Colombo'),
('Amara', 'Silva', 'N1234567V', '0719876543', 'amara.s@example.com', '45 Kandy Road, Kandy');

INSERT INTO bookings (guest_id, room_id, check_in_date, check_out_date, num_guests, status, total_amount, created_by) VALUES
(2, 4, '2026-07-10', '2026-07-13', 2, 'CHECKED_IN', 40500.00, 2);

INSERT INTO payments (booking_id, amount, payment_method, received_by) VALUES
(1, 40500.00, 'CARD', 2);
